### ISSUE TITLE
Erro na execução de um dos exemplos.

### ISSUE THREAD

**Issue by rtio** [kriansa/h2p#15]
E aí, blz? Estou tentando executar um dos exemplos e está me retornando esse erro. Fiz teste em uma distribuição linux e em um windows 7. No linux compilei o executável e no windows fiz o download. Vi que tem mais gente com o mesmo problema, o que seria?

Fatal error: Uncaught exception 'H2P\Exception' with message 'Error while executing PhantomJS: "SyntaxError: JSON Parse error: Expected '}'"' in 
C:\xampp\htdocs\h2p\src\H2P\Converter\PhantomJS.php on line 283 H2P\Exception: Error while executing PhantomJS: "SyntaxError: JSON Parse error: Expected '}'" in C:\xampp\htdocs\h2p\src\H2P\Converter\PhantomJS.php on line 283

**Comment by Fabyo** [comment]
Estou com o mesmo problema da erro:  "SyntaxError: JSON Parse error: Expected '}'"

**Comment by Seb33300** [comment]
I solved this issue using the solution here: https://github.com/kriansa/h2p/issues/14

**Comment by kriansa** [comment]
Este é o mesmo problema #14.
