### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by realnerdo** [kriansa/h2p#17]
Hello, I like h2p so much, but I get an error when running. I'm sorry if it's a newbie question:
```php
Fatal error: Class 'H2P\Converter' not found in /var/www/public/index.php on line 15
```

This is my index.php
It's located in `public/index.php` and my `composer.json` and `vendor` folder are in the root.
```php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use H2P\Converter;
use H2P\Converter\PhantomJS;
use H2P\TempFile;

// Set the input content to convert $input = new TempFile($htmlString);
$input = 'http://www.google.com/';
// $input = '/path/to/file.html';

// Then do the conversion $output = new TempFile();
$output = new TempFile();
$instance = new Converter(new PhantomJS(), $input, $output);
$instance->convert();

// Save it somewhere $output->save('/another/path/to/file.pdf');
// or output it header('Pragma: public');
header('Expires: 0');
header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
header('Content-Type: application/pdf');
header('Content-Transfer-Encoding: binary');
header('Content-Length: ' . filesize($output->getFileName()));
echo $output->getContent();
```
This is the line where I get the error:
```php
...
$instance = new Converter(new PhantomJS(), $input, $output);
...
```
I already required the vendor autoload but I can't pass that error.

Thank you for your help.

— Asael

**Comment by kriansa** [comment]
Somehow the autoloader is not being able to locate the class.

Are you really using composer? If so, you should be using composer's autoload instead H2P's...

Take a look here https://getcomposer.org/doc/01-basic-usage.md

**Comment by Clearmist** [comment]
@realnerdo please paste your composer.json here so I can look at it. Also, do you mean that composer.json is in **/var/www/**composer.json or **/var/www/public/**composer.json?
