### ISSUE TITLE
Erro geração do pdf

### ISSUE THREAD

**Issue by Fabyo** [kriansa/h2p#18]
Nao estou conseguindo rodar nem o exemplo
instalei via composer, copiei o executavel para pasta certa mas mesmo assim da erro

 'Error while executing PhantomJS: "SyntaxError: JSON Parse error: Expected '}'"' 

eu tentei a dica em outro topico falando para nao usar escapeshellarg no windows mas nada funcionou

poderia ajudar?
obrigado

**Comment by Seb33300** [comment]
I solved this issue using the solution here:
https://github.com/kriansa/h2p/issues/14

**Comment by kriansa** [comment]
Este é o mesmo problema #14.

**Comment by Fabyo** [comment]
Obrigado pelo retorno, mas eu tinha testado ja essa opção mas ele da o mesmo erro

eu ate testei no ambiente linux tbm nao rodou

sera que o phantom nao teve alguma atualização critica?, porque o H2P esta desatualizado a 3 anos talvez precise mexer em alguma coisa

**Comment by Fabyo** [comment]
Daniel só reportando, deu certo, agora esta gerando normalmente no windows

obrigado
